name: Linux Web Android Build

on:
  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.5
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin' # See https://github.com/marketplace/actions/setup-java-jdk#supported-distributions for available options
        java-version: '21'

    - name: Patch for build
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget makeself poppler-utils
        flutter doctor

    - name: Flet Build Prepare
      run: |
        flutter config --no-analytics # disable flutter analytics
        chmod +x ./runConfigurations/ScriptPrepare.sh
        chmod +x ./runConfigurations/ScriptBuild.sh
        ./runConfigurations/ScriptPrepare.sh

    - name: Flet Build Linux
      run: |
        ./runConfigurations/ScriptBuild.sh linux
      shell: bash

    - name: Flet Build Web
      run: |
        ./runConfigurations/ScriptBuild.sh web
        zip web.zip ./builds/web/* -r
        
      shell: bash

    - name: Flet Build Android
      run: |
        ./runConfigurations/ScriptBuild.sh android
      shell: bash

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4.3.4  # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: linux-build-artifact  # the name of the artifact
        path: ./builds/linux/citynav-linux.run  # location of Flet build output
        if-no-files-found: error  # Fail the action with an error message if no files are found
        overwrite: false  # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    - name: Upload Web Artifact
      uses: actions/upload-artifact@v4.3.4  # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: web-build-artifact  # the name of the artifact
        path: web.zip  # location of Flet build output
        if-no-files-found: error  # Fail the action with an error message if no files are found
        overwrite: false

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4  # https://github.com/marketplace/actions/upload-a-build-artifact
      with:
        name: android-build-artifact  # the name of the artifact
        path: ./builds/android/app-release.apk  # location of Flet build output
        if-no-files-found: error  # Fail the action with an error message if no files are found
        overwrite: false
